name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup Rust
      uses: raftario/setup-rust-action@v1

    - name: Setup wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 2.x
        architecture: x64

    - name: Install dependencies
      run: npm ci
    
    - name: Build wasm and package
      run: npm run build
      env:
        CI: true

    - name: Run unit tests
      run: npm run test:ci
      env:
        CI: true

    - name: Build release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm i -g semantic-release@17 @semantic-release/git@9 @semantic-release/changelog@5
        semantic-release